### PR TITLE
Add license please!

### PR DESCRIPTION
**Pull request by ateesdalejr**
The original repository has switched to the MIT license. I'd greatly appreciate it if this fork complied as well.

### CODE REVIEW

**Comment by ateesdalejr** [comment]
Thanks! 👍 Might want to delete the branch now. Actually no need to. 📦

**Comment by RedMAngo22** [comment]
Hey!

**Comment by ateesdalejr** [comment]
@RedMAngo22 Hello!

**Comment by ateesdalejr** [comment]
@RedMAngo22 Hello!

**Pull request merged**
